name: tasker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.3
  percent_indicator: ^4.2.3
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_localization: ^0.2.0
  firebase_core: ^2.25.2
  firebase_messaging: ^14.7.13
  firebase_storage: ^11.6.4
  firebase_auth: ^4.17.3
  animated_icon: ^0.0.5
  flutter_svg: ^2.0.9
  flutter_sliding_up_panel: ^2.1.1
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
